[Logging to './logs/application.log']
[Logging to './logs/application.trace']
 _______  _______  _______  _______    _______ _________ _______  _______ _________ _______  _______  _______   
(  ___  )(  ____ \(       )(  ____ \  (  ____ \\__   __/(  ___  )(  ____ )\__   __/(  ____ \(  ____ )(  ____ \  
| (   ) || (    \/| () () || (    \/  | (    \/   ) (   | (   ) || (    )|   ) (   | (    \/| (    )|| (    \/  
| (___) || |      | || || || (__      | (_____    | |   | (___) || (____)|   | |   | (__    | (____)|| (_____   
|  ___  || |      | |(_)| ||  __)     (_____  )   | |   |  ___  ||     __)   | |   |  __)   |     __)(_____  )  
| (   ) || |      | |   | || (              ) |   | |   | (   ) || (\ (      | |   | (      | (\ (         ) |  
| )   ( || (____/\| )   ( || (____/\  /\____) |   | |   | )   ( || ) \ \__   | |   | (____/\| ) \ \__/\____) |  
|/     \|(_______/|/     \|(_______/  \_______)   )_(   |/     \||/   \__/   )_(   (_______/|/   \__/\_______)  
                                                                                                                                    

Application endpoint: http://localhost:8080/Acme-Starters-C
Database endpoint:    jdbc:mariadb://localhost:3307/Acme-Starters-C?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
Powered by:           Java EE 21.0.5, Spring Boot 2.7.18, Acme Framework 26.3.0

Starting Launcher using Java 21.0.5 on Sinenomine with PID 33704 (C:\Users\juanp\Workspace-26\Workspace-26\Frameworks\Acme-Framework-26.3.0\target\classes started by juanp in C:\Users\juanp\Workspace-26\Workspace-26\Projects\DP2-2526-G010) 
The following 3 profiles are active: "development", "application", "run" 
ERROR Failed to initialize JPA EntityManagerFactory: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)] 
WARN  Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)] 
ERROR Application run failed at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)] at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421): [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)] at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:159): Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)]
ERROR org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)]
org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421): [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)]
org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:159): Schema-validation: wrong column type encountered in column [end_moment] in table [sponsorship]; found [tinyblob (Types#VARBINARY)], but expecting [datetime(6) (Types#TIMESTAMP)] 
Exiting application with status 1. 
The log might provide further details. 